[[redirects]]
  from = "/api/*"
  to = "http://3.15.16.150:8090/api/:splat"
  status = 200

[[redirects]]
  from = "https://3.15.16.150:8090/resources/*"
  to = "http://3.15.16.150:8090/resources/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  